spring.application.name=QuizApp
spring.datasource.url=jdbc:postgresql://localhost:5432/questionsdb
spring.datasource.username=postgres
spring.datasource.password=patil@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
java -jar your-application.jar --debug
#server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-cu8lm6350x8ip525.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://quizapi,https://questionapi



